### ISSUE TITLE
apt via https

### ISSUE THREAD

**Issue by pstauffer** [pstauffer/kubernetes-setup#6]
```
- name: add certificates
  apt:
    name: '{{ item }}'
    state: present
  with_items:
  - ca-certificates
  - apt-transport-https
```
